name: Build and Publish Elsa Packages
on:
  workflow_dispatch:

env:
  NODE_OPTIONS: --max-old-space-size=4096
  ELSA_VERSION: 2.14.1-1

jobs:
  build_and_pack:
    name: Build and Pack Elsa
    runs-on: ubuntu-latest

    steps:

      - name: Set preview VERSION variable
        run: echo "VERSION=$ELSA_VERSION-preview.${{ github.run_number }}" >> $GITHUB_ENV
        if: ${{ github.event_name != 'release' }}

      - name: Set release VERSION variable
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'release' }}

      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Build Elsa
        run: dotnet build --configuration Release /p:Version=$VERSION

      - name: Pack Elsa
        run: dotnet pack --configuration Release /p:Version=$VERSION /p:PackageOutputPath=$(pwd)/out 

      - name: Upload Elsa Artifact
        uses: actions/upload-artifact@v3
        with:
          name: elsa-nuget-package
          path: out/*nupkg

  publish_nuget_release:
    name: Publish to Nuget
    needs: build_and_pack
    runs-on: ubuntu-latest
    steps:
      - name: Download Nuget Packages
        uses: actions/download-artifact@v3
        with:
          name: elsa-nuget-package
      
      - name: Publish Nuget Packages to MyGet
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
